accounts/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import LogoutView
from accounts import views

app_name = "accounts"

urlpatterns = [

    path(
        'login/', views.AccountLoginView.as_view(), name='login_view'),


    # logout user
    path(
        'logout/',
        LogoutView.as_view(next_page='accounts:login_view'),
        name="logout_view"),


    # change password view
    path(
        'password/change',
        views.ChangePasswordView.as_view(), name='change_password'),


    # signup view
    path(
        'signup/', views.SignUpView.as_view(), name='signup_view'),


    # activate account view (check activation tokens)
    path(
        'activate/<str:uidb64>/<str:token>/',
        views.ActivateAccountView.as_view(), name='activate_account_view'),


    # show form for resetting password
    path(
        'lost_password/',
        views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'),
        name='reset_password'),


    path(
        'lost_password/confirm/<str:uidb64>/<str:token>',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),


    path(
        'lost_password/done',
        PasswordResetDoneView.as_view(
            template_name='accounts/registration/password_reset_done.html'),
        name='password_reset_done'),


    path(
        'lost_password/complete',
        PasswordResetCompleteView.as_view(
            template_name="accounts/registration/password_reset_complete.html"),
        name='password_reset_complete'),


    path('', views.Index.as_view(), name="index"),


    path('profile/user/<str:user_id>', views.ShowUserProfile.as_view(), name='user_profile'),


    path(
        'profile/user/<str:user_id>/found/vulns',
        views.ListVulnsFoundByUser.as_view(), name='user_found_vulns'),


    path(
        'profile/refresh_api_token',
        views.RefreshAPIToken.as_view(),
        name="refresh_api_token"),


    path(
        'profile/change_email',
        views.ChangeEMailAddressView.as_view(),
        name="change_email_address"),


    path(
        'profile/change_email/confirm/<str:uidb64>/<str:token>',
        views.ValidateChangeEMailAddressView.as_view(),
        name="confirm_change_email_address"),


    path(
        'profile/settings', views.Settings.as_view(),
        name="settings"),

    path('dashboard', views.Dashboard.as_view(), name="dashboard")
]

api/urls.py
from django.urls import path, include
from rest_framework.authtoken import views

app_name = "api"

urlpatterns = [
    path('pentesting/', include('pentesting.api.urls')),
    path('bug_bounty_mode/', include('bug_bounty_mode.api.urls')),
    # path('projects/', include('projects.api.urls')),
    path('blogs/', include('blogging.api.urls')),
    path('stats/', include('stats.api.urls')),
    path('accounts/', include('accounts.api.urls')),
    path('mailbox/', include('cymailbox.api.urls')),
]

cysec_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('public_pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('activity-feed/', include('activity_feed.urls')),
    path('blogs/', include('blogging.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('bugbounty/', include('bug_bounty_mode.urls')),
    path('tasks/', include('todoz.urls')),
    path('pentesting/', include('pentesting.urls')),
    path('mailbox/', include('cymailbox.urls')),
    path('api/', include('api.urls')),
    path('api_docs', include_docs_urls(title='CySec-Server API', public=False)),
    path('api-token-auth/', obtain_auth_token),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pentesting/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from pentesting.api import views

app_name = 'pentesting-api'

urlpatterns = [
    path('projects/<int:pk>/top-services', views.TopServices.as_view(), name='top-services'),
    path('projects/<int:pk>/services-per-host', views.ServicesPerHost.as_view(), name='services-per-host'),
    path('projects/<int:pk>/vulnerabilities-by-severity', views.VulnerabilitiesBySeverity.as_view(), name='vulnerabilities-by-severity'),
]

router = DefaultRouter()
router.register(r'command', views.CommandViewSet, basename='command')
router.register(r'project', views.ProjectViewSet, basename='project')
router.register(r'hosts', views.HostViewSet, basename='host')
router.register(r'hostnames', views.HostnameViewSet, basename='hostname')
router.register(r'services', views.ServiceViewSet, basename='service')
router.register(r'credentials', views.CredentialViewSet, basename='credential')

urlpatterns += router.urls

pentesting/urls.py
from django.urls import path
from pentesting import views

app_name = 'pentesting'

urlpatterns = [

    path('projects', views.AllProjects.as_view(), name='all-projects'),
    path('projects/new', views.CreateProject.as_view(), name='create-project'),
    path('project', views.SingleProject.as_view(), name='single-project'),
    path('project/settings', views.Settings.as_view(), name='project-settings'),
    path('project/add-user', views.AddUserToProject.as_view(), name='add-user-to-project'),
    path('project/switch/<int:pk>', views.SwitchActiveProject.as_view(), name='switch-project'),
    path('project/<str:slug>/delete', views.DeleteProject.as_view(), name='delete-project'),

    path('project/reports', views.Reports.as_view(), name='reports'),
    path('project/reports/new', views.CreateReport.as_view(), name='create-report'),
    path('project/reports/new/encrypted', views.CreateEncryptedReport.as_view(), name='create-encrypted-report'),
    path('project/reports/<int:pk>/<str:b64id>/<str:token>', views.DownloadReport.as_view(), name='download-report'),

    path('social-engineering/credentials', views.AllCredentials.as_view(), name='all-credentials'),
    path('social-engineering/credentials/new', views.CreateCredential.as_view(), name='create-credential'),

    path('network/hosts', views.AllHosts.as_view(), name='all-hosts'),
    path('network/hosts/new', views.CreateHost.as_view(), name='create-host'),
    path('network/hosts/<str:slug>', views.SingleHost.as_view(), name='single-host'),
    path('network/hosts/<str:slug>/edit', views.EditHost.as_view(), name='edit-host'),
    path('network/hosts/<str:slug>/delete', views.DeleteHost.as_view(), name='delete-host'),

    path('network/hosts/<str:host_slug>/services/new', views.CreateService.as_view(), name='create-service'),
    path('network/hosts/<str:host_slug>/services/<str:slug>', views.SingleService.as_view(), name='single-service'),
    path('network/hosts/<str:host_slug>/services/<str:slug>/edit', views.EditService.as_view(), name='edit-service'),
    path('network/hosts/<str:host_slug>/services/<str:slug>/delete', views.DeleteService.as_view(), name='delete-service'),

    path('network/hosts/<str:host_slug>/hostnames/new', views.CreateHostname.as_view(), name='create-hostname'),
    path('network/hosts/<str:host_slug>/hostnames/<int:pk>/edit', views.EditHostname.as_view(), name='edit-hostname'),
    path('network/hosts/<str:host_slug>/hostnames/<int:pk>/delete', views.DeleteHostname.as_view(), name='delete-hostname'),

    path('vulnerabilities/<str:service_slug>/flaws/general/new', views.CreateVulnerability.as_view(), name='create-vulnerability'),
    path('vulnerabilities/<str:service_slug>/flaws/general/<int:pk>', views.SingleVulnerability.as_view(), name='single-vulnerability'),
    path('vulnerabilities/<str:service_slug>/flaws/general/<int:pk>/edit', views.EditVulnerability.as_view(), name='edit-vulnerability'),

    path('vulnerabilities/<str:service_slug>/flaws/web/new', views.CreateWebVulnerability.as_view(), name='create-web-vulnerability'),
    path('vulnerabilities/<str:service_slug>/flaws/web/<int:pk>', views.SingleWebVulnerability.as_view(), name='single-web-vulnerability'),
    path('vulnerabilities/<str:service_slug>/flaws/web/<int:pk>/edit', views.EditWebVulnerability.as_view(), name='edit-web-vulnerability'),

]

pentesting/forms.py
from django import forms
from pentesting import models


class ProjectForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ('name', 'due_date')


class CredentialForm(forms.ModelForm):
    class Meta:
        model = models.Credential
        fields = ('username', 'password', 'name', 'service')
        # TODO: service queryset filtering for project services only


class HostForm(forms.ModelForm):
    class Meta:
        model = models.Host
        fields = ('ip', 'os', 'mac', 'owned')


class ServiceForm(forms.ModelForm):
    class Meta:
        model = models.Service
        fields = ('name', 'port', 'protocol', 'version')


class HostnameForm(forms.ModelForm):
    class Meta:
        model = models.Hostname
        fields = ('name', )


class VulnerabilityForm(forms.ModelForm):
    class Meta:
        model = models.Vulnerability
        fields = ('name', 'service', 'severity', 'description', 'poc', 'approved')
        # TODO: filter only for allowed services


class WebVulnerabilityForm(forms.ModelForm):
    class Meta:
        model = models.WebVulnerability
        fields = ('name', 'service', 'severity', 'description', 'poc', 'hostname', 'path', 'param', 'approved')
        # TODO: filter hostname and service


class EncryptedReportForm(forms.ModelForm):
    class Meta:
        model = models.EncryptedReport
        fields = ('algorithm', 'template')


class ReportForm(forms.ModelForm):
    class Meta:
        model = models.Report
        fields = ('template', )


class UserProjectForm(forms.ModelForm):
    class Meta:
        model = models.UserProject
        fields = ('user', 'role')

pentesting/api/views.py
from rest_framework import generics
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from django.db.models import Count, Q
from pentesting.api import serializers
from pentesting import models


class TopServices(generics.RetrieveAPIView):
    permission_classes = [IsAuthenticated]

    def retrieve(self, request, *args, **kwargs):
        user_project = get_object_or_404(models.UserProject, user=self.request.user, project__pk=self.kwargs.get('pk'))
        queryset = models.Host.objects.filter(
            project=user_project.project).values('service__name').annotate(count=Count('service__pk')).order_by('-count')[:5]
        return Response(queryset)


class ServicesPerHost(generics.RetrieveAPIView):
    permission_classes = [IsAuthenticated]

    def retrieve(self, request, *args, **kwargs):
        user_project = get_object_or_404(models.UserProject, user=self.request.user, project__pk=self.kwargs.get('pk'))
        queryset = models.Host.objects.filter(project=user_project.project).values('ip').annotate(count=Count('service')).order_by('-count')[:5]
        return Response(queryset)


class VulnerabilitiesBySeverity(generics.RetrieveAPIView):
    permission_classes = [IsAuthenticated]

    def retrieve(self, request, *args, **kwargs):
        user_project = get_object_or_404(models.UserProject, user=self.request.user, project__pk=self.kwargs.get('pk'))
        queryset = models.Severity.objects.filter(
            Q(vulnerability__service__host__project=user_project.project)|Q(vulnerability__isnull=True)).values('name', 'color').annotate(count=Count('vulnerability__pk'))
        return Response(queryset)


class CreateVulnerability(generics.CreateAPIView):
    pass


class UpdateVulnerability(generics.UpdateAPIView):
    pass


class AllVulnerabilities(generics.ListAPIView):
    pass


class DeleteVulnerability(generics.DestroyAPIView):
    pass


class SingleVulnerability(generics.RetrieveAPIView):
    pass


class CommandViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = serializers.CommandSerializer

    def get_queryset(self):
        return models.ExecutedCommand.objects.filter(project__userproject__user=self.request.user)

    def perform_create(self, serializer):
        get_object_or_404(models.Project, userproject__user=self.request.user, pk=serializer.validated_data.get('project').pk)
        return super(CommandViewSet, self).perform_create(serializer)


class ProjectViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = serializers.ProjectSerializer

    def get_queryset(self):
        return models.Project.objects.filter(userproject__user=self.request.user)


class HostViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = serializers.HostSerializer

    def perform_create(self, serializer):
        get_object_or_404(models.Project, userproject__user=self.request.user, pk=serializer.validated_data.get('project').pk)
        super(HostViewSet, self).perform_create(serializer)

    def get_queryset(self):
        return models.Host.objects.filter(project__userproject__user=self.request.user)


class HostnameViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = serializers.HostnameSerializer

    def perform_create(self, serializer):
        get_object_or_404(models.Host, project__userproject__user=self.request.user, pk=serializer.validated_data.get('host').pk)
        super(HostnameViewSet, self).perform_create(serializer)

    def get_queryset(self):
        return models.Hostname.objects.filter(host__project__userproject__user=self.request.user)


class ServiceViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = serializers.ServiceSerializer

    def perform_create(self, serializer):
        get_object_or_404(models.Host, project__userproject__user=self.request.user, pk=serializer.validated_data.get('host').pk)
        return super(ServiceViewSet, self).perform_create(serializer)

    def get_queryset(self):
        return models.Service.objects.filter(host__project__userproject__user=self.request.user)


class CredentialViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = serializers.CredentialSerializer

    def perform_create(self, serializer):
        get_object_or_404(models.Service, host__project__userproject__user=self.request.user, pk=serializer.validated_data.get('service').pk)
        return super(CredentialViewSet, self).perform_create(serializer)

    def get_queryset(self):
        return models.Credential.objects.filter(service__host__project__userproject__user=self.request.user)

pentesting/templates/pentesting/vulnerabilities/create_vulnerability.html
{% extends 'base.html' %}


{% block content %}

    <h3 class="text-center">Create Vulnerability</h3>
    <hr />

    <form class="form" method="post">
        {% csrf_token %}
        {% include 'generic/form.html' %}
        <button class="btn btn-info float-right mt-3">Create</button>
    </form>

{% endblock content %}

pentesting/templates/pentesting/vulnerabilities/edit_vulnerability.html
{% extends 'base.html' %}

{% block title %}Edit {{ vulnerability }}{% endblock title %}

{% block content %}

<h3 class="text-center">Edit Vulnerability</h3>
<hr />

<form class="form" method="POST">
    {% csrf_token %}
    {% include 'generic/form.html' %}

    <a href="{# url 'delete_vulnerability' vuln.service.host.pk vuln.service.pk vuln.pk #}" class="btn btn-danger">
        Delete
    </a>
    <button class="btn btn-info float-right">Save</button>
</form>

{% endblock content %}

pentesting/templates/pentesting/vulnerabilities/edit_web_vulnerability.html
{% extends 'base.html' %}

{% block title %}Edit {{ vulnerability }}{% endblock title %}

{% block content %}

<h3 class="text-center">Edit Web Vulnerability</h3>
<hr />

<form class="form" method="POST">
    {% csrf_token %}
    {% include 'generic/form.html' %}

    <a href="{# url 'delete_vulnerability' vuln.service.host.pk vuln.service.pk vuln.pk #}" class="btn btn-danger">
        Delete
    </a>
    <button class="btn btn-info float-right">Save</button>
</form>

{% endblock content %}

pentesting/templates/pentesting/vulnerabilities/single_vulnerability.html
{% extends 'base.html' %}

{% block title %}{{ vulnerability }}{% endblock title %}

{% block content %}

    <div class="clearfix">
        {% if not vuln.fixed %}
            <span class="badge badge-pill badge-danger float-right ml-2">Unpatched!</span>
        {% else %}
            <span class="badge badge-pill badge-success float-right ml-2">Patched!</span>
        {% endif %}
        <h3 class="text-center">{{ vulnerability }} on {{ vulnerability.service.host.ip }}</h3>
    </div>

    <hr />

    <div class="card mt-3">
        <div class="card-body">
            <p><strong>Vulnerability: </strong>{{ vulnerability.name }}</p>
            <p><strong>Service: </strong>{{ vulnerability.service }}</p>
            <p><strong>Severity: </strong>{{ vulnerability.severity }}</p>
            <p>
                <strong>User: </strong>
                <a href="{% url 'accounts:user_profile' vulnerability.user.pk %}">{{ vulnerability.user.username }}</a>
            </p>
            <p><strong>Proof of Concept: </strong>{{ vulnerability.poc|linebreaksbr }}</p>
        </div>

        {% if request.user == vulnerability.user %}
            <div class="card-footer">
                <div class="clearfix">
                    <a href="{% url 'pentesting:edit-vulnerability' vulnerability.service.slug vulnerability.pk %}" class="btn btn-primary btn-sm rounded float-right">
                        <i class="fa fa-edit"></i>
                        Edit
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

pentesting/templates/pentesting/vulnerabilities/single_web_vulnerability.html
{% extends 'base.html' %}

{% block title %}{{ vulnerability }}{% endblock title %}

{% block content %}

    <div class="clearfix">
        {% if not vuln.fixed %}
            <span class="badge badge-pill badge-danger float-right ml-2">Unpatched!</span>
        {% else %}
            <span class="badge badge-pill badge-success float-right ml-2">Patched!</span>
        {% endif %}
        <h3 class="text-center">{{ vulnerability }} on {{ vulnerability.hostname }}</h3>
    </div>

    <hr />

    <div class="card mt-3">
        <div class="card-body">
            <p><strong>Vulnerability: </strong>{{ vulnerability.name }}</p>
            <p><strong>Service: </strong>{{ vulnerability.service }}</p>
            <p><strong>Severity: </strong>{{ vulnerability.severity }}</p>
            <p>
                <strong>User: </strong>
                <a href="{% url 'accounts:user_profile' vulnerability.user.pk %}">{{ vulnerability.user.username }}</a>
            </p>
            <p><strong>Hostname: </strong>{{ vulnerability.hostname }}</p>
            <p><strong>Path: </strong>{{ vulnerability.path }}</p>
            <p><strong>Parameter: </strong>{{ vulnerability.param }}</p>
            <p><strong>Proof of Concept: </strong>{{ vulnerability.poc|linebreaksbr }}</p>
        </div>

        {% if request.user == vulnerability.user %}
            <div class="card-footer">
                <div class="clearfix">
                    <a href="{% url 'pentesting:edit-web-vulnerability' vulnerability.service.slug vulnerability.pk %}" class="btn btn-primary btn-sm rounded float-right">
                        <i class="fa fa-edit"></i>
                        Edit
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}